### ISSUE TITLE
Typo in find_deformations.jl at line 120

### ISSUE THREAD

**Issue by Shangjun-Cheng** [RainerHeintzmann/FindShift.jl#5]
Hi Rainer,

I noticed a small typo in the file find_deformations.jl at line 120. _Returned **ia** a tuple of the aligned images and a vector of warps to perform the transform for any other images via the "warp" call._

The word "ia" should be corrected to "is".

Best regards,
Shangjun

**Comment by RainerHeintzmann** [comment]
Thanks. Corrected.
